services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    networks:
      - sga

  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - sga

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sga_bojanini
    command: --log-bin-trust-function-creators=1 --default-time-zone=-05:00
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sga

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command: php artisan queue:work --tries=3 --timeout=90 --sleep=3
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - sga

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - sga

volumes:
  mysql_data:

networks:
  sga:
